var app = app || {};

(function(){

	app.levels = 
	[
		{
			objects: 
			[
				{
					url: 'img/level1/dino.png',
					x: 700,
					y: 150,
					width: 100,
					height: 100,
					score: 10,
					velocity: 5,
					toLeft: true,
					duration: 0,
				},
				{
					url: 'img/level1/mammoth.png',
					x: 0,
					y: 200,
					width: 100,
					height: 100,
					score: 5,
					velocity: 8,
					duration: 1000,
				},
				{
					url: 'img/level1/dino.png',
					x: 0,
					y: 250,
					width: 70,
					height: 70,
					score: 10,
					velocity: 5,
					duration: 2000,
					
				},
				{
					url: 'img/level1/mammoth.png',
					x: 730,
					y: 200,
					width: 70,
					height: 70,
					score: 5,
					velocity: 8,
					toLeft: true,
					duration: 3000,
				},
				{
					url: 'img/level1/mammoth.png',
					x: 785,
					y: 50,
					width: 15,
					height: 15,
					score: 40,
					velocity: 25,
					toLeft:true,
					duration: 5000,
				},
				{
					url: 'img/level1/mammoth.png',
					x: 0,
					y: 250,
					width: 50,
					height: 50,
					score: 20,
					velocity: 3,
					duration: 6000,
				},
				{
					url: 'img/level1/dino.png',
					x: 780,
					y: 300,
					width: 20,
					height: 20,
					score: 35,
					velocity: 20,
					toLeft: true,
					duration: 7000,
				},
				{
					url: 'img/level1/dino.png',
					x: 10,
					y: 100,
					width: 10,
					height: 10,
					score: 50,
					velocity: 30,
					duration: 8000,
				},
				{
					url: 'img/level1/dino.png',
					x: 750,
					y: 250,
					width: 60,
					height: 60,
					score: 30,
					velocity: 2,
					toLeft: true,
					duration: 9000,
				},
				{
					url: 'img/level1/dino.png',
					x: 750,
					y: 200,
					width: 80,
					height: 80,
					score: 30,
					velocity: 10,
					toLeft: true,
					duration: 10000,
				}
			]
		},
		{
			objects: 
			[
				{
					url: 'img/level2/elk.png',
					x: 0,
					y: 200,
					width: 120,
					height: 120,
					score: 10,
					velocity: 10,
					duration: 0,
				},
				{
					url: 'img/level2/sheep.png',
					x: 700,
					y: 300,
					width: 96,
					height: 80,
					score: 5,
					velocity: 8,
					duration: 500,
					toLeft: true,
				},
				{
					url: 'img/level2/skunk.png',
					x: 710,
					y: 410,
					width: 90,
					height: 90,
					score: -20,
					velocity: 5,
					duration: 1300,
					toLeft: true,
					toTop: true,
				},
				{
					url: 'img/level2/butterfly.png',
					x: 0,
					y: 60,
					width: 50,
					height: 50,
					score: 20,
					velocity: 10,
					duration: 1800,
					fly: true,
				},
				{
					url: 'img/level2/elk.png',
					x: 0,
					y: 200,
					width: 54,
					height: 54,
					score: 20,
					velocity: 6,
					duration: 2500,
				},
				{
					url: 'img/level2/flower.png',
					x: 650,
					y: 54,
					width: 54,
					height: 54,
					score: 20,
					velocity: 10,
					duration: 3000,
					toLeft: true,
				},
				{
					url: 'img/level2/skunk.png',
					x: 710,
					y: 370,
					width: 90,
					height: 90,
					score: -20,
					velocity: 15,
					duration: 2000,
					toLeft: true,
					fly: true,
				},
				{
					url: 'img/level2/owl.png',
					x: 800,
					y: 100,
					width: 54,
					height: 54,
					score: 10,
					velocity: 4,
					duration: 3500,
					toLeft: true,
				},
				{
					url: 'img/level2/sheep.png',
					x: 0,
					y: 350,
					width: 48,
					height: 40,
					score: 20,
					velocity: 8,
					duration: 5000,
					fly: true,
				},
				{
					url: 'img/level2/skunk.png',
					x: 0,
					y: 370,
					width: 70,
					height: 70,
					score: -30,
					velocity: 4,
					duration: 2000,
					fly: true,
				},
				{
					url: 'img/level2/owl.png',
					x: 0,
					y: 100,
					width: 35,
					height: 35,
					score: 30,
					velocity: 8,
					duration: 6500,
					fly: true,
				},
				{
					url: 'img/level2/flower.png',
					x: 0,
					y: 100,
					width: 40,
					height: 40,
					score: 30,
					velocity: 10,
					duration: 7000,
				},

				{
					url: 'img/level2/elk.png',
					x: 0,
					y: 200,
					width: 60,
					height: 60,
					score: 20,
					velocity: 10,
					duration: 8000,
				},
				{
					url: 'img/level2/owl.png',
					x: 750,
					y: 100,
					width: 35,
					height: 35,
					score: 30,
					velocity: 5,
					duration: 8500,
					fly: true,
					toLeft: true,
				},
				{
					url: 'img/level2/sheep.png',
					x: 700,
					y: 200,
					width: 96,
					height: 80,
					score: 5,
					velocity: 3,
					duration: 9000,
					toLeft: true,
				},
				{
					url: 'img/level2/skunk.png',
					x: 0,
					y: 420,
					width: 40,
					height: 40,
					score: -20,
					velocity: 5,
					duration: 10000,
					fly: true,
				},
				{
					url: 'img/level2/elk.png',
					x: 0,
					y: 200,
					width: 80,
					height: 80,
					score: 15,
					velocity: 3,
					duration: 10000,
				},
				{
					url: 'img/level2/butterfly.png',
					x: 0,
					y: 30,
					width: 50,
					height: 50,
					score: 15,
					velocity: 8,
					duration: 11000,
					fly: true,
				},
				{
					url: 'img/level2/butterfly.png',
					x: 0,
					y: 50,
					width: 50,
					height: 50,
					score: 15,
					velocity: 8,
					duration: 11000,
					fly: true,
				},
				{
					url: 'img/level2/butterfly.png',
					x: 0,
					y: 70,
					width: 50,
					height: 50,
					score: 15,
					velocity: 8,
					duration: 11000,
					fly: true,
				},
				{
					url: 'img/level2/butterfly.png',
					x: 0,
					y: 90,
					width: 50,
					height: 50,
					score: 15,
					velocity: 8,
					duration: 11000,
					fly: true,
				},
				{
					url: 'img/level2/elk.png',
					x: 0,
					y: 200,
					width: 120,
					height: 120,
					score: 10,
					velocity: 10,
					duration: 12000,
				},
				{
					url: 'img/level2/sheep.png',
					x: 700,
					y: 300,
					width: 96,
					height: 80,
					score: 5,
					velocity: 8,
					duration: 12000,
					toLeft: true,
				},
				{
					url: 'img/level2/elk.png',
					x: 0,
					y: 250,
					width: 100,
					height: 100,
					score: 10,
					velocity: 10,
					duration: 12500,
				},
				{
					url: 'img/level2/sheep.png',
					x: 700,
					y: 250,
					width: 70,
					height: 60,
					score: 5,
					velocity: 8,
					duration: 12500,
					toLeft: true,
				},
				{
					url: 'img/level2/sheep.png',
					x: 0,
					y: 350,
					width: 48,
					height: 40,
					score: 20,
					velocity: 3,
					duration: 12500,
					fly: true,
				},
				{
					url: 'img/level2/skunk.png',
					x: 0,
					y: 420,
					width: 40,
					height: 40,
					score: -20,
					velocity: 5,
					duration: 13000,
					fly: true,
				},
				{
					url: 'img/level2/flower.png',
					x: 650,
					y: 50,
					width: 50,
					height: 50,
					score: 30,
					velocity: 6,
					duration: 14000,
					toLeft: true,
				},
				{
					url: 'img/level2/flower.png',
					x: 50,
					y: 50,
					width: 50,
					height: 50,
					score: 30,
					velocity: 6,
					duration: 14000,
				},
			]
		}
	];

})();